### ISSUE TITLE
Tournoi

### ISSUE THREAD

**Issue by dimtion** [TeamRoquette/PyRat#2]
Houston on a un problème : http://formations.telecom-bretagne.eu/pyrat/?page_id=39

**Comment by nimag42** [comment]
Techniquement "votre bot doit se déplacer de manière plus intelligente que votre adversaire", si mon adversaire ne se déplace pas, on se déplace bien de manière plus intelligente non ?

**Comment by dimtion** [comment]
Il vaut mieux ne pas se déplacer et passer pour un idiot, que se déplacer
et laisser aucun doute sur le sujet.
Le 12 oct. 2015 10:04 AM, "Jacquin Théo" notifications@github.com a
écrit :

**Comment by nimag42** [comment]
Dixit l'homme sage.

**Comment by dimtion** [comment]
Problème résolu.
